"""Generate a self-contained script to run inside SecureCRT."""

from ipaddress import IPv4Address
import json
from pathlib import Path
import re
import sys

from .device_console import environment_values


def generate(report, output, username=None, port=22, interactive=False, credentials=None, root=None):
    if not 1 <= port <= 65535:
        raise ValueError("SSH port must be between 1 and 65535")
    if credentials is not None and not credentials.strip():
        raise ValueError("SecureCRT credential title must not be empty")
    if credentials is not None and username is not None:
        raise ValueError("Use either --credentials or --username; saved credentials supply the username")
    leases = list(report["leases"])
    if root is not None:
        for key, value in sorted(environment_values(Path(root)).items()):
            if not key.endswith('_MANAGEMENT_IP') or not value.strip():
                continue
            hostname = key[:-len('_MANAGEMENT_IP')]
            if not hostname:
                raise ValueError('Management IP variable requires a hostname prefix')
            try:
                address = str(IPv4Address(value.strip()))
            except ValueError:
                raise ValueError(f'{key} must contain a valid IPv4 address') from None
            leases.append({'status': 'permanent', 'ip_address': address, 'hostname': hostname})
    sessions = {}
    for lease in leases:
        if lease["status"] not in ("active", "permanent"):
            continue
        address = str(IPv4Address(lease["ip_address"]))
        hostname = re.sub(r"[^A-Za-z0-9_.-]+", "_", lease.get("hostname") or "").strip("._")[:80]
        name = "eve/" + (hostname + " - " if hostname else "") + address
        sessions[address] = {"name": name, "host": address, "username": username or "", "port": port, "hostname": hostname}
    records = sorted(sessions.values(), key=lambda item: IPv4Address(item["host"]))
    used = set()
    for record in records:
        hostname = record.pop("hostname")
        if not interactive:
            continue
        default = hostname or record["host"]
        if default.casefold() in used:
            default += " - " + record["host"]
        base = default
        suffix = 2
        while default.casefold() in used:
            default = base + " - " + str(suffix)
            suffix += 1
        while True:
            try:
                print("{} — session name [{}]: ".format(record["host"], default), end="", file=sys.stderr, flush=True)
                name = input().strip() or default
            except (EOFError, KeyboardInterrupt):
                raise ValueError("Session generation cancelled; output file was not changed") from None
            if (name in (".", "..") or name.endswith(".") or
                    re.search(r'[\\/:*?"<>|\x00-\x1f\x7f]', name) or
                    re.fullmatch(r"(?i:CON|PRN|AUX|NUL|COM[0-9]|LPT[0-9])(?:\..*)?", name)):
                print("Use a session name without path separators, reserved names, or special characters.", file=sys.stderr)
                continue
            if name.casefold() in used:
                print("That session name is already used in this export; choose another.", file=sys.stderr)
                continue
            used.add(name.casefold())
            record["name"] = "eve/" + name
            break
    # Encode data separately so DHCP hostnames can never become executable code.
    script = '''# $language = "Python"
# $interface = "1.0"
import json

# Generated by eve. Run using SecureCRT: Script > Run.

sessions = json.loads(DATA)
credentials = CREDENTIALS
created = 0
updated = 0
for item in sessions:
    try:
        config = crt.OpenSessionConfiguration(item["name"])
        exists = True
    except Exception:
        config = crt.OpenSessionConfiguration("Default")
        exists = False
    config.SetOption("Protocol Name", "SSH2")
    config.SetOption("Hostname", item["host"])
    config.SetOption("[SSH2] Port", item["port"])
    config.SetOption("Prompt For Credential Title", 0)
    if credentials is not None:
        config.SetOption("Credential Title", credentials)
    else:
        config.SetOption("Credential Title", "")
        config.SetOption("Username", item["username"])
    config.Save(item["name"])
    if exists:
        updated += 1
    else:
        created += 1
crt.Dialog.MessageBox("EVE sessions: {} created, {} updated. Close and reopen Session Manager to refresh.".format(created, updated))
'''.replace("json.loads(DATA)", "json.loads(" + repr(json.dumps(records, ensure_ascii=True)) + ")")
    script = script.replace("credentials = CREDENTIALS", "credentials = " + ascii(credentials))
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(script, encoding="utf-8")
    return {"output": str(output.resolve()), "folder": "eve", "session_count": len(records),
            "sessions": [record["name"] for record in records],
            "next_step": "In SecureCRT, choose Script > Run and select the generated file"}
